import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Base64; 

// Java program to calculate MD5 hash value 
public class MD5 { 
	public static String getMd5(String input) 
	{ 
		try { 

			byte[] messageDigest = getMD5ByteArray(input); 

			// Convert byte array into signum representation 
			BigInteger no = new BigInteger(1, messageDigest); 

			// Convert message digest into hex value 
			String hashtext = no.toString(16); 
			while (hashtext.length() < 32) { 
				hashtext = "0" + hashtext; 
			} 
			return hashtext; 
		} 

		// For specifying wrong message digest algorithms 
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	}

	private static byte[] getMD5ByteArray(String input) throws NoSuchAlgorithmException {
		// Static getInstance method is called with hashing MD5 
		MessageDigest md = MessageDigest.getInstance("MD5"); 

		// digest() method is called to calculate message digest 
		// of an input digest() return array of byte 
		byte[] messageDigest = md.digest(input.getBytes());
		return messageDigest;
	} 

	public static String base64Encoder(byte[] byteArr) {
		
		 Base64.Encoder encoder = Base64.getEncoder();  
		 byte[] a = encoder.encode(byteArr);
		 
		 return new String(a);
		
	}
	// Driver code 
	public static void main(String args[]) throws NoSuchAlgorithmException 
	{ 
		String s = "GeeksForGeeks"; 
//		System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s)); 
		
		String s1 = base64Encoder(getMD5ByteArray(s));
		System.out.println(s1);
		
	} 
} 
